[package]
name = "wasmtime-rb"
version = "9.0.4"
edition = "2021"
authors = ["The Wasmtime Project Developers"]
license = "Apache-2.0"
publish = false
build = "build.rs"

[features]
default = ["tokio", "all-arch"]
embed = ["magnus/embed"]
tokio = ["dep:tokio", "dep:async-timer"]
all-arch = ["wasmtime/all-arch"]
ruby-api = []
winch = ["wasmtime/winch"]

[dependencies]
lazy_static = "1.4.0"
magnus = { version = "0.5.5", features = ["rb-sys-interop"] }
rb-sys = { version = "*", default-features = false, features = [
  "stable-api-compiled-fallback",
] }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "83cf743" }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", rev = "83cf743" }
wasi-common = { git = "https://github.com/bytecodealliance/wasmtime", rev = "83cf743" }
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/wasmtime", rev = "83cf743" }
cap-std = "2.0.0"
anyhow = "*" # Use whatever Wasmtime uses
wat = "1.0.86"
tokio = { version = "1.28.2", features = [
  "rt",
  "rt-multi-thread",
  "time",
  "net",
], optional = true }
async-timer = { version = "1.0.0-beta.11", features = [
  "tokio1",
], optional = true }
static_assertions = "1.1.0"
wasmtime-runtime = "= 15.0.0"
wasmtime-environ = "= 15.0.0"

[build-dependencies]
rb-sys-env = "0.1.2"
